"""
Django settings for OpsMate project.
Generated by 'django-admin startproject' using Django 3.1.3.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k8h3s6+71nf##cbv0tf(to5-559e=2*5f(dek6^&j8d268%$#4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# STATICFILES_FINDERS = (
#    "django.contrib.staticfiles.finders.FileSystemFinder",
#    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
# )

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Added by Selin
    'patch_management.apps.PatchManagementConfig',
    'rest_framework',
    'corsheaders',  # Only for development

    # Added by Trung
    'django_celery_results',
    'django_celery_beat',
]


REST_FRAMEWORK = {
    '   ': (
        'rest_framework.renderers.JSONRenderer',
    )
}

# REST_FRAMEWORK = {
#  "DATETIME_FORMAT": ["%d-%m-%Y"],
#  "DEFAULT_RENDERER_CLASSES": (
#      "rest_framework.renderers.JSONRenderer",
#     "rest_framework.renderers.BrowsableAPIRenderer",
#     "rest_framework_datatables.renderers.DatatablesRenderer",
# ),
# }


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Only for development
]

ROOT_URLCONF = 'OpsMate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'patch_frontend/build')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OpsMate.wsgi.application'

MESSAGE_TAGS = {
    messages.DEBUG: 'text-success',
    messages.INFO: 'text-info',
    messages.SUCCESS: 'text-primary',
    messages.WARNING: 'text-warning',
    messages.ERROR: 'text-danger',
}


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
# Dev Config

# Prod Config
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql', # for Patchmanagement
#         'NAME': 'patches',
#         'USER': 'mysqluser',
#         'PASSWORD': 'mysqlpassword',
#         'HOST': 'opstool-mariadb',
#         'PORT': '3306'
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
