# Generated by Django 3.1.3 on 2021-02-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupServerDetail',
            fields=[
                ('backup_server', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('server_ip', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, default='in-production', max_length=50)),
                ('backup_url', models.CharField(blank=True, max_length=50)),
                ('created_by', models.CharField(default='Admin', editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCriticality',
            fields=[
                ('criticality', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_by', models.CharField(default='Admin', editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('account_name', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('smtp_mail_server', models.CharField(blank=True, max_length=50)),
                ('from_address', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('itsm_api_url', models.CharField(blank=True, max_length=50)),
                ('created_by', models.CharField(default='Admin', editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorServerDetail',
            fields=[
                ('monitor_server', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('server_ip', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, default='in-production', max_length=50)),
                ('monitor_url', models.CharField(blank=True, max_length=50)),
                ('created_by', models.CharField(default='Admin', editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.globalconfig')),
            ],
        ),
        migrations.CreateModel(
            name='PatchDetail',
            fields=[
                ('patch_id', models.CharField(blank=True, max_length=25, primary_key=True, serialize=False)),
                ('patch_name', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True)),
                ('technology_id', models.CharField(blank=True, max_length=25)),
                ('created_by', models.CharField(default='Admin', editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatchJob',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_no', models.CharField(max_length=10)),
                ('planned_startdate', models.DateTimeField(blank=True)),
                ('planned_enddate', models.DateTimeField(blank=True)),
                ('actual_startdate', models.DateTimeField(blank=True)),
                ('actual_enddate', models.DateTimeField(blank=True)),
                ('created_by', models.CharField(default='Admin', editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('patch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.patchdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ServerDetail',
            fields=[
                ('server_name', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('os_name', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, default='in-production', max_length=50)),
                ('credential_path', models.CharField(blank=True, max_length=50)),
                ('backup_enabled', models.BooleanField(default=False)),
                ('monitor_enabled', models.BooleanField(default=False)),
                ('created_by', models.CharField(default='Admin', editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('backup_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.backupserverdetail')),
                ('criticality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.businesscriticality')),
                ('monitor_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.monitorserverdetail')),
            ],
        ),
        migrations.CreateModel(
            name='SeverityRating',
            fields=[
                ('severity', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_by', models.CharField(default='Admin', editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_id', models.CharField(blank=True, max_length=25)),
                ('technology_name', models.CharField(max_length=50)),
                ('created_by', models.CharField(default='Admin', editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationSummary',
            fields=[
                ('validation_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_name', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('prepatch_outputpath', models.CharField(max_length=150)),
                ('postpatch_outputpath', models.CharField(max_length=150)),
                ('created_by', models.CharField(default='Admin', editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.patchjob')),
                ('patch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.patchdetail')),
                ('server_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.serverdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PatchSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('patch_executiondate', models.DateTimeField(blank=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('kernel_version', models.CharField(max_length=50)),
                ('created_by', models.CharField(default='Admin', editable=False, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.patchjob')),
                ('patch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.patchdetail')),
                ('server_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.serverdetail')),
            ],
        ),
        migrations.AddField(
            model_name='patchdetail',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.severityrating'),
        ),
        migrations.AddField(
            model_name='backupserverdetail',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patch_management.globalconfig'),
        ),
    ]
